<?php

return [
    'countries' => [
        'Andorra',
        'United Arab Emirates',
        'Afghanistan',
        'Antigua and Barbuda',
        'Anguilla',
        'Albania',
        'Armenia',
        'Angola',
        'Antarctica',
        'Argentina',
        'American Samoa',
        'Austria',
        'Australia',
        'Aruba',
        'Alland Islands',
        'Azerbaijan',
        'Bosnia and Herzegovina',
        'Barbados',
        'Bangladesh',
        'Belgium',
        'Burkina Faso',
        'Bulgaria',
        'Bahrain',
        'Burundi',
        'Benin',
        'Saint Barthelemy',
        'Bermuda',
        'Brunei Darussalam',
        'Bolivia',
        'Brazil',
        'Bahamas',
        'Bhutan',
        'Bouvet Island',
        'Botswana',
        'Belarus',
        'Belize',
        'Canada',
        'Cocos (Keeling) Islands',
        'Congo Democratic Republic of the',
        'Central African Republic',
        'Congo Republic of the',
        'Switzerland',
        'Coted Ivoire',
        'Cook Islands',
        'Chile',
        'Cameroon',
        'China',
        'Colombia',
        'Costa Rica',
        'Cuba',
        'Cape Verde',
        'Curacao',
        'Christmas Island',
        'Cyprus',
        'Czech Republic',
        'Germany',
        'Djibouti',
        'Denmark',
        'Dominica',
        'Dominican Republic',
        'Algeria',
        'Ecuador',
        'Estonia',
        'Egypt',
        'Western Sahara',
        'Eritrea',
        'Spain',
        'Ethiopia',
        'Finland',
        'Fiji',
        'Falkland Islands (Malvinas)',
        'Micronesia Federated States of',
        'Faroe Islands',
        'France',
        'Gabon',
        'United Kingdom',
        'Grenada',
        'Georgia',
        'French Guiana',
        'Guernsey',
        'Ghana',
        'Gibraltar',
        'Greenland',
        'Gambia',
        'Guinea',
        'Guadeloupe',
        'Equatorial Guinea',
        'Greece',
        'South Georgia and the South Sandwich Islands',
        'Guatemala',
        'Guam',
        'Guinea-Bissau',
        'Guyana',
        'Hong Kong',
        'Heard Island and McDonald Islands',
        'Honduras',
        'Croatia',
        'Haiti',
        'Hungary',
        'Indonesia',
        'Ireland',
        'Israel',
        'Isle of Man',
        'India',
        'British Indian Ocean Territory',
        'Iraq',
        'Iran Islamic Republic of',
        'Iceland',
        'Italy',
        'Jersey',
        'Jamaica',
        'Jordan',
        'Japan',
        'Kenya',
        'Kyrgyzstan',
        'Cambodia',
        'Kiribati',
        'Comoros',
        'Saint Kitts and Nevis',
        'Korea Democratic People s Republic of',
        'Korea Republic of',
        'Kuwait',
        'Cayman Islands',
        'Kazakhstan',
        'Lao People s Democratic Republic',
        'Lebanon',
        'Saint Lucia',
        'Liechtenstein',
        'Sri Lanka',
        'Liberia',
        'Lesotho',
        'Lithuania',
        'Luxembourg',
        'Latvia',
        'Libya',
        'Morocco',
        'Monaco',
        'Moldova Republic of',
        'Montenegro',
        'Saint Martin (French part)',
        'Madagascar',
        'Marshall Islands',
        'Macedonia the Former Yugoslav Republic of',
        'Mali',
        'Myanmar',
        'Mongolia',
        'Macao',
        'Northern Mariana Islands',
        'Martinique',
        'Mauritania',
        'Montserrat',
        'Malta',
        'Mauritius',
        'Maldives',
        'Malawi',
        'Mexico',
        'Malaysia',
        'Mozambique',
        'Namibia',
        'New Caledonia',
        'Niger',
        'Norfolk Island',
        'Nigeria',
        'Nicaragua',
        'Netherlands',
        'Norway',
        'Nepal',
        'Nauru',
        'Niue',
        'New Zealand',
        'Oman',
        'Panama',
        'Peru',
        'French Polynesia',
        'Papua New Guinea',
        'Philippines',
        'Pakistan',
        'Poland',
        'Saint Pierre and Miquelon',
        'Pitcairn',
        'Puerto Rico',
        'Palestine State of',
        'Portugal',
        'Palau',
        'Paraguay',
        'Qatar',
        'Reunion',
        'Romania',
        'Serbia',
        'Russian Federation',
        'Rwanda',
        'Saudi Arabia',
        'Solomon Islands',
        'Seychelles',
        'Sudan',
        'Sweden',
        'Singapore',
        'Saint Helena',
        'Slovenia',
        'Svalbard and Jan Mayen',
        'Slovakia',
        'Sierra Leone',
        'San Marino',
        'Senegal',
        'Somalia',
        'Suriname',
        'South Sudan',
        'Sao Tome and Principe',
        'El Salvador',
        'Sint Maarten (Dutch part)',
        'Syrian Arab Republic',
        'Swaziland',
        'Turks and Caicos Islands',
        'Chad',
        'French Southern Territories',
        'Togo',
        'Thailand',
        'Tajikistan',
        'Tokelau',
        'Timor-Leste',
        'Turkmenistan',
        'Tunisia',
        'Tonga',
        'Turkey',
        'Trinidad and Tobago',
        'Tuvalu',
        'Taiwan Republic of China',
        'United Republic of Tanzania',
        'Ukraine',
        'Uganda',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Holy See (Vatican City State)',
        'Saint Vincent and the Grenadines',
        'Venezuela',
        'British Virgin Islands',
        'US Virgin Islands',
        'Vietnam',
        'Vanuatu',
        'Wallis and Futuna',
        'Samoa',
        'Kosovo',
        'Yemen',
        'Mayotte',
        'South Africa',
        'Zambia',
        'Zimbabwe',
    ],

    'timezones' => [
        'Europe/Andorra',
        'Asia/Dubai',
        'Asia/Kabul',
        'Europe/Tirane',
        'Asia/Yerevan',
        'Antarctica/Casey',
        'Antarctica/Davis',
        'Antarctica/DumontDUrville',
        'Antarctica/Mawson',
        'Antarctica/Palmer',
        'Antarctica/Rothera',
        'Antarctica/Syowa',
        'Antarctica/Troll',
        'Antarctica/Vostok',
        'America/Argentina/Buenos_Aires',
        'America/Argentina/Cordoba',
        'America/Argentina/Salta',
        'America/Argentina/Jujuy',
        'America/Argentina/Tucuman',
        'America/Argentina/Catamarca',
        'America/Argentina/La_Rioja',
        'America/Argentina/San_Juan',
        'America/Argentina/Mendoza',
        'America/Argentina/San_Luis',
        'America/Argentina/Rio_Gallegos',
        'America/Argentina/Ushuaia',
        'Pacific/Pago_Pago',
        'Europe/Vienna',
        'Australia/Lord_Howe',
        'Antarctica/Macquarie',
        'Australia/Hobart',
        'Australia/Currie',
        'Australia/Melbourne',
        'Australia/Sydney',
        'Australia/Broken_Hill',
        'Australia/Brisbane',
        'Australia/Lindeman',
        'Australia/Adelaide',
        'Australia/Darwin',
        'Australia/Perth',
        'Australia/Eucla',
        'Asia/Baku',
        'America/Barbados',
        'Asia/Dhaka',
        'Europe/Brussels',
        'Europe/Sofia',
        'Atlantic/Bermuda',
        'Asia/Brunei',
        'America/La_Paz',
        'America/Noronha',
        'America/Belem',
        'America/Fortaleza',
        'America/Recife',
        'America/Araguaina',
        'America/Maceio',
        'America/Bahia',
        'America/Sao_Paulo',
        'America/Campo_Grande',
        'America/Cuiaba',
        'America/Santarem',
        'America/Porto_Velho',
        'America/Boa_Vista',
        'America/Manaus',
        'America/Eirunepe',
        'America/Rio_Branco',
        'America/Nassau',
        'Asia/Thimphu',
        'Europe/Minsk',
        'America/Belize',
        'America/St_Johns',
        'America/Halifax',
        'America/Glace_Bay',
        'America/Moncton',
        'America/Goose_Bay',
        'America/Blanc-Sablon',
        'America/Toronto',
        'America/Nipigon',
        'America/Thunder_Bay',
        'America/Iqaluit',
        'America/Pangnirtung',
        'America/Atikokan',
        'America/Winnipeg',
        'America/Rainy_River',
        'America/Resolute',
        'America/Rankin_Inlet',
        'America/Regina',
        'America/Swift_Current',
        'America/Edmonton',
        'America/Cambridge_Bay',
        'America/Yellowknife',
        'America/Inuvik',
        'America/Creston',
        'America/Dawson_Creek',
        'America/Fort_Nelson',
        'America/Vancouver',
        'America/Whitehorse',
        'America/Dawson',
        'Indian/Cocos',
        'Europe/Zurich',
        'Africa/Abidjan',
        'Pacific/Rarotonga',
        'America/Santiago',
        'America/Punta_Arenas',
        'Pacific/Easter',
        'Asia/Shanghai',
        'Asia/Urumqi',
        'America/Bogota',
        'America/Costa_Rica',
        'America/Havana',
        'Atlantic/Cape_Verde',
        'America/Curacao',
        'Indian/Christmas',
        'Asia/Nicosia',
        'Asia/Famagusta',
        'Europe/Prague',
        'Europe/Berlin',
        'Europe/Copenhagen',
        'America/Santo_Domingo',
        'Africa/Algiers',
        'America/Guayaquil',
        'Pacific/Galapagos',
        'Europe/Tallinn',
        'Africa/Cairo',
        'Africa/El_Aaiun',
        'Europe/Madrid',
        'Africa/Ceuta',
        'Atlantic/Canary',
        'Europe/Helsinki',
        'Pacific/Fiji',
        'Atlantic/Stanley',
        'Pacific/Chuuk',
        'Pacific/Pohnpei',
        'Pacific/Kosrae',
        'Atlantic/Faroe',
        'Europe/Paris',
        'Europe/London',
        'Asia/Tbilisi',
        'America/Cayenne',
        'Africa/Accra',
        'Europe/Gibraltar',
        'America/Godthab',
        'America/Danmarkshavn',
        'America/Scoresbysund',
        'America/Thule',
        'Europe/Athens',
        'Atlantic/South_Georgia',
        'America/Guatemala',
        'Pacific/Guam',
        'Africa/Bissau',
        'America/Guyana',
        'Asia/Hong_Kong',
        'America/Tegucigalpa',
        'America/Port-au-Prince',
        'Europe/Budapest',
        'Asia/Jakarta',
        'Asia/Pontianak',
        'Asia/Makassar',
        'Asia/Jayapura',
        'Europe/Dublin',
        'Asia/Jerusalem',
        'Asia/Kolkata',
        'Indian/Chagos',
        'Asia/Baghdad',
        'Asia/Tehran',
        'Atlantic/Reykjavik',
        'Europe/Rome',
        'America/Jamaica',
        'Asia/Amman',
        'Asia/Tokyo',
        'Africa/Nairobi',
        'Asia/Bishkek',
        'Pacific/Tarawa',
        'Pacific/Enderbury',
        'Pacific/Kiritimati',
        'Asia/Pyongyang',
        'Asia/Seoul',
        'Asia/Almaty',
        'Asia/Qyzylorda',
        'Asia/Qostanay',
        'Asia/Aqtobe',
        'Asia/Aqtau',
        'Asia/Atyrau',
        'Asia/Oral',
        'Asia/Beirut',
        'Asia/Colombo',
        'Africa/Monrovia',
        'Europe/Vilnius',
        'Europe/Luxembourg',
        'Europe/Riga',
        'Africa/Tripoli',
        'Africa/Casablanca',
        'Europe/Monaco',
        'Europe/Chisinau',
        'Pacific/Majuro',
        'Pacific/Kwajalein',
        'Asia/Yangon',
        'Asia/Ulaanbaatar',
        'Asia/Hovd',
        'Asia/Choibalsan',
        'Asia/Macau',
        'America/Martinique',
        'Europe/Malta',
        'Indian/Mauritius',
        'Indian/Maldives',
        'America/Mexico_City',
        'America/Cancun',
        'America/Merida',
        'America/Monterrey',
        'America/Matamoros',
        'America/Mazatlan',
        'America/Chihuahua',
        'America/Ojinaga',
        'America/Hermosillo',
        'America/Tijuana',
        'America/Bahia_Banderas',
        'Asia/Kuala_Lumpur',
        'Asia/Kuching',
        'Africa/Maputo',
        'Africa/Windhoek',
        'Pacific/Noumea',
        'Pacific/Norfolk',
        'Africa/Lagos',
        'America/Managua',
        'Europe/Amsterdam',
        'Europe/Oslo',
        'Asia/Kathmandu',
        'Pacific/Nauru',
        'Pacific/Niue',
        'Pacific/Auckland',
        'Pacific/Chatham',
        'America/Panama',
        'America/Lima',
        'Pacific/Tahiti',
        'Pacific/Marquesas',
        'Pacific/Gambier',
        'Pacific/Port_Moresby',
        'Pacific/Bougainville',
        'Asia/Manila',
        'Asia/Karachi',
        'Europe/Warsaw',
        'America/Miquelon',
        'Pacific/Pitcairn',
        'America/Puerto_Rico',
        'Asia/Gaza',
        'Asia/Hebron',
        'Europe/Lisbon',
        'Atlantic/Madeira',
        'Atlantic/Azores',
        'Pacific/Palau',
        'America/Asuncion',
        'Asia/Qatar',
        'Indian/Reunion',
        'Europe/Bucharest',
        'Europe/Belgrade',
        'Europe/Kaliningrad',
        'Europe/Moscow',
        'Europe/Simferopol',
        'Europe/Kirov',
        'Europe/Astrakhan',
        'Europe/Volgograd',
        'Europe/Saratov',
        'Europe/Ulyanovsk',
        'Europe/Samara',
        'Asia/Yekaterinburg',
        'Asia/Omsk',
        'Asia/Novosibirsk',
        'Asia/Barnaul',
        'Asia/Tomsk',
        'Asia/Novokuznetsk',
        'Asia/Krasnoyarsk',
        'Asia/Irkutsk',
        'Asia/Chita',
        'Asia/Yakutsk',
        'Asia/Khandyga',
        'Asia/Vladivostok',
        'Asia/Ust-Nera',
        'Asia/Magadan',
        'Asia/Sakhalin',
        'Asia/Srednekolymsk',
        'Asia/Kamchatka',
        'Asia/Anadyr',
        'Asia/Riyadh',
        'Pacific/Guadalcanal',
        'Indian/Mahe',
        'Africa/Khartoum',
        'Europe/Stockholm',
        'Asia/Singapore',
        'America/Paramaribo',
        'Africa/Juba',
        'Africa/Sao_Tome',
        'America/El_Salvador',
        'Asia/Damascus',
        'America/Grand_Turk',
        'Africa/Ndjamena',
        'Indian/Kerguelen',
        'Asia/Bangkok',
        'Asia/Dushanbe',
        'Pacific/Fakaofo',
        'Asia/Dili',
        'Asia/Ashgabat',
        'Africa/Tunis',
        'Pacific/Tongatapu',
        'Europe/Istanbul',
        'America/Port_of_Spain',
        'Pacific/Funafuti',
        'Asia/Taipei',
        'Europe/Kiev',
        'Europe/Uzhgorod',
        'Europe/Zaporozhye',
        'Pacific/Wake',
        'America/New_York',
        'America/Detroit',
        'America/Kentucky/Louisville',
        'America/Kentucky/Monticello',
        'America/Indiana/Indianapolis',
        'America/Indiana/Vincennes',
        'America/Indiana/Winamac',
        'America/Indiana/Marengo',
        'America/Indiana/Petersburg',
        'America/Indiana/Vevay',
        'America/Chicago',
        'America/Indiana/Tell_City',
        'America/Indiana/Knox',
        'America/Menominee',
        'America/North_Dakota/Center',
        'America/North_Dakota/New_Salem',
        'America/North_Dakota/Beulah',
        'America/Denver',
        'America/Boise',
        'America/Phoenix',
        'America/Los_Angeles',
        'America/Anchorage',
        'America/Juneau',
        'America/Sitka',
        'America/Metlakatla',
        'America/Yakutat',
        'America/Nome',
        'America/Adak',
        'Pacific/Honolulu',
        'America/Montevideo',
        'Asia/Samarkand',
        'Asia/Tashkent',
        'America/Caracas',
        'Asia/Ho_Chi_Minh',
        'Pacific/Efate',
        'Pacific/Wallis',
        'Pacific/Apia',
        'Africa/Johannesburg'
    ],

    'currencies' => [
        'EUR',
        'USD',
        'JPY',
        'BTC',
        'GBP',
    ],

    'roles' => [
        'Administrator',
        'Editor',
    ],

    'times' => [
        'repeats',
        'specific',
    ],
    'question_type' => [
        'type',
        'yes_no',
        'multiple_choice',
    ]
];
